#spring:
#  datasource:
#    url: jdbc:postgresql://hopper.proxy.rlwy.net:15601/railway
#    username: postgres
#    password: dtyHnMdaOnuipMZXbvcwntORMdpUwHZx
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sf_adminpanel
    username: sf_admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
file:
  storage:
    path: /documents


minio:
  url: https://bucket-production-f3af.up.railway.app:443
  accessKey: prX6NbIzkAabISpgrdUWSLmlnwHa5hP7
  secretKey: QEWj0MEbxzFSaoKJqQuAI0If6JqNIPZydRBm6ZScj8CLb49A
  bucket: test-bucket




